version: '3.9'
services:
  web:
    build: .
    # command: ./start_docker_development.sh
    volumes:
      - .:/resource_quotable
    environment:
      BUNDLE_APP_CONFIG: /resource_quotable/.bundle
    ports:
      - "3000:3000"
